// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Webhook.Data;

#nullable disable

namespace Webhook.Data.Migrations
{
    [DbContext(typeof(WebhookDbContext))]
    [Migration("20260628112322_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Webhook.Data.Models.Alert", b =>
                {
                    b.Property<Guid>("AlertID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StockChange")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockID")
                        .HasColumnType("uuid");

                    b.HasKey("AlertID");

                    b.HasIndex("AlertID")
                        .IsUnique();

                    b.HasIndex("StockID");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("Webhook.Data.Models.Distributor", b =>
                {
                    b.Property<Guid>("DistributorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SitemapUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DistributorID");

                    b.HasIndex("DistributorID")
                        .IsUnique();

                    b.ToTable("Distributors");
                });

            modelBuilder.Entity("Webhook.Data.Models.FufilmentChannel", b =>
                {
                    b.Property<Guid>("FufilmentChannelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FufilmentChannelID");

                    b.HasIndex("FufilmentChannelID")
                        .IsUnique();

                    b.ToTable("fufilmentChannels");
                });

            modelBuilder.Entity("Webhook.Data.Models.Location", b =>
                {
                    b.Property<Guid>("LocationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistributorID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LocationID");

                    b.HasIndex("DistributorID");

                    b.HasIndex("LocationID")
                        .IsUnique();

                    b.HasIndex("ReferenceID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("Webhook.Data.Models.Product", b =>
                {
                    b.Property<Guid>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DistributorID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FufilmentChannelID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPreOrder")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreOrderDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductImgUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProductID");

                    b.HasIndex("DistributorID");

                    b.HasIndex("FufilmentChannelID");

                    b.HasIndex("ProductID")
                        .IsUnique();

                    b.HasIndex("ReferenceID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Webhook.Data.Models.Stock", b =>
                {
                    b.Property<Guid>("StockID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("LocationID")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uuid");

                    b.Property<int>("StockAvailable")
                        .HasColumnType("integer");

                    b.Property<Guid>("StockTypeID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StockID");

                    b.HasIndex("ProductID");

                    b.HasIndex("StockID")
                        .IsUnique();

                    b.HasIndex("StockTypeID");

                    b.ToTable("Stock");
                });

            modelBuilder.Entity("Webhook.Data.Models.StockType", b =>
                {
                    b.Property<Guid>("StockTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReferenceID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StockTypeID");

                    b.HasIndex("StockTypeID")
                        .IsUnique();

                    b.ToTable("StockTypes");
                });

            modelBuilder.Entity("Webhook.Data.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("User", "USERS");
                });

            modelBuilder.Entity("Webhook.Data.Models.WebhookConnection", b =>
                {
                    b.Property<Guid>("WebhookConnectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistributorID")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("StockTypeID")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WebhookConnectionID");

                    b.HasIndex("DistributorID");

                    b.HasIndex("StockTypeID");

                    b.HasIndex("WebhookConnectionID")
                        .IsUnique();

                    b.ToTable("WebhookConnections");
                });

            modelBuilder.Entity("Webhook.Data.Models.Alert", b =>
                {
                    b.HasOne("Webhook.Data.Models.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("Webhook.Data.Models.Location", b =>
                {
                    b.HasOne("Webhook.Data.Models.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("Webhook.Data.Models.Product", b =>
                {
                    b.HasOne("Webhook.Data.Models.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webhook.Data.Models.FufilmentChannel", "FufilmentChannel")
                        .WithMany()
                        .HasForeignKey("FufilmentChannelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");

                    b.Navigation("FufilmentChannel");
                });

            modelBuilder.Entity("Webhook.Data.Models.Stock", b =>
                {
                    b.HasOne("Webhook.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webhook.Data.Models.StockType", "StockType")
                        .WithMany()
                        .HasForeignKey("StockTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockType");
                });

            modelBuilder.Entity("Webhook.Data.Models.WebhookConnection", b =>
                {
                    b.HasOne("Webhook.Data.Models.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webhook.Data.Models.StockType", "StockType")
                        .WithMany()
                        .HasForeignKey("StockTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distributor");

                    b.Navigation("StockType");
                });
#pragma warning restore 612, 618
        }
    }
}
