<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.28" />
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.11" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Extensions" Version="2.3.11" />
    <PackageReference Include="Microsoft.Net.Http.Headers" Version="8.0.28" />
    <PackageReference Include="Microsoft.Playwright" Version="1.61.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.19.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Webhook.Data\Webhook.Data.csproj" />
    <ProjectReference Include="..\Webhook.Util\Webhook.Util.csproj" />
  </ItemGroup>

</Project>
