# Given an appsettings.json file like this,
#{
#  "ConnectionStrings": {
#    "DefaultConnection": "Data Source=LocalSqlServer\\MSSQLDev;"
#  },
#  "Logging": {
#    "LogLevel": {
#      "Default": "Information",
#      "Microsoft": "Warning",
#      "Microsoft.Hosting.Lifetime": "Information"
#    }
#  },
#  "AllowedHosts": "*"
#}

# This is an example environment.conf file that sets the environment variables for the application

# Top-level keys can just sit at the top without a section
# AllowedHosts=*

# [ConnectionStrings]
# DefaultConnection=Data Source=LocalSqlServer\MSSQLDev;

# [Logging:LogLevel]
# Default=Information
# Microsoft=Warning
# Microsoft.Hosting.Lifetime=Information